language: elixir
elixir:
  - 1.3.0
otp_release:
  - 18.1
before_script:
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
